### ISSUE TITLE
Launcher sound track volume dangerously loud

### ISSUE THREAD

**Issue by fanzypantz** [SphereII/7D2DModLauncher#2]
I might have destroyed my headphones partially because of this.

At 50% windows sound and no gain on amplifier the music playing in the launcher left me with ringing in the ears and probably a destroyed headset in certain frequencies. Probably lower the volume a tiny bit..

**Comment by SphereII** [comment]
What sound track did you hear? The mod launcher does not play music.

**Comment by fanzypantz** [comment]
I downloaded the source file version on accident. That version played music.
